"""v0.3 memory study: HBM4 plan and using LPDDR when HBM is the bottleneck.

    python3 -m model.memory_study     # writes results/memory_study.md

v0.3 decisions (locked): FP4 KV cache, 10% scheduler speed tolerance, 48 tiles.
Memory options compared:
  * HBM3E vs HBM4 main memory
  * DDR weight share: stream a bandwidth-proportional slice of the weights from
    LPDDR in parallel with HBM (more bandwidth, frees HBM, costs more pJ/byte)
  * reduced-HBM and LPDDR-only products for when HBM supply or cost is the limit
All assumptions for HBM4 and wide LPDDR are marked below; none are vendor data.
"""
import os
from dataclasses import replace

from .hw import EnergyTable
from .study import D, SRV, SUITE, evaluate, score, _t

V03_SRV = replace(SRV, kv_dtype="fp4")

# --- memory building blocks (assumptions) ---------------------------------
HBM4 = dict(hbm_gen="HBM4", hbm_tbps=8.2, hbm_gb=192.0, hbm_phy_scale=1.3,   # 4 x (2048 b x 8 Gb/s, 48 GB)
            energy=replace(EnergyTable(), hbm_pj_per_byte=20.0))
WIDE_LPDDR = dict(lpddr_tbps=1.09, lpddr_gb=512.0, lpddr_phy_scale=2.0)      # 16 x64 ch @ 8533 MT/s, 16 x 32 GB
PKG_W, STACK_W = 0.375, 2.0          # idle W per LPDDR package / per HBM stack (in fixed static)


def with_static(chip, stacks, lp_pkgs):
    """Adjust fixed static power for a different memory population (baseline: 4 stacks, 8 packages)."""
    delta = STACK_W * (stacks - 4) + PKG_W * (lp_pkgs - 8)
    return replace(chip, node=replace(chip.node, fixed_static_w=chip.node.fixed_static_w + delta))


V02 = D
DEC = replace(D, speed_slack=0.10)                                       # decisions on HBM3E
V03 = replace(DEC, **HBM4)                                               # + HBM4
V03_SHARE = replace(V03, weight_ddr_share=V03.balanced_ddr_share)
_wide = with_static(replace(V03, **WIDE_LPDDR), 4, 16)
V03_WIDE = replace(_wide, weight_ddr_share=_wide.balanced_ddr_share)
_half = with_static(replace(V03, hbm_stacks=2, hbm_tbps=4.1, hbm_gb=96.0, **WIDE_LPDDR), 2, 16)
HALF_HBM = replace(_half, weight_ddr_share=_half.balanced_ddr_share)
LP_ONLY = with_static(replace(DEC, hbm_stacks=0, hbm_tbps=0.0, hbm_gb=0.0, **WIDE_LPDDR), 0, 16)
LP_ONLY_XL = with_static(replace(DEC, hbm_stacks=0, hbm_tbps=0.0, hbm_gb=0.0,
                                 lpddr_tbps=1.64, lpddr_gb=768.0, lpddr_phy_scale=3.0), 0, 24)

VARIANTS = [
    ("v0.2", "Reference: HBM3E, FP8 KV, 2% tolerance", V02, SRV),
    ("v0.2 + decisions", "HBM3E, FP4 KV, 10% tolerance", DEC, V03_SRV),
    ("**v0.3**", "HBM4 ×4 (8.2 TB/s, 192 GB) + LPDDR 256 GB tier", V03, V03_SRV),
    ("v0.3 + DDR share", "Same, plus ~6% of weights streamed from LPDDR", V03_SHARE, V03_SRV),
    ("v0.3 + wide DDR", "HBM4 ×4 + 16-ch LPDDR (1.09 TB/s, 512 GB), ~12% weight share", V03_WIDE, V03_SRV),
    ("Half-HBM SKU", "HBM4 ×2 (4.1 TB/s, 96 GB) + 16-ch LPDDR, ~21% weight share", HALF_HBM, V03_SRV),
    ("LPDDR-only SKU", "No HBM, no interposer: 16-ch LPDDR 1.09 TB/s, 512 GB", LP_ONLY, V03_SRV),
    ("LPDDR-only XL", "No HBM: 24-ch LPDDR 1.64 TB/s, 768 GB", LP_ONLY_XL, V03_SRV),
]


def mem_desc(c):
    hbm = f"{c.hbm_stacks}× {c.hbm_gen} {c.hbm_tbps:.1f} TB/s" if c.has_hbm else "none"
    return hbm, f"{c.lpddr_gb:.0f} GB · {c.lpddr_tbps:.2f} TB/s", f"{c.ddr_share:.0%}"


def main():
    base = evaluate(V02, SRV)
    res = [(n, d, c, s, evaluate(c, s)) for n, d, c, s in VARIANTS]
    parts = ["# v0.3 memory study: HBM4 and LPDDR reuse\n",
             "_Generated by `python3 -m model.memory_study`. v0.3 decisions: FP4 KV cache, 10% scheduler "
             "tolerance, 48 tiles, 3nm. Ratios vs v0.2. HBM4 (20 pJ/B, 2.05 TB/s per stack) and wide-LPDDR "
             "figures are planning assumptions, not vendor data._\n"]

    rows = []
    for n, d, c, s, r in res:
        hbm, lp, share = mem_desc(c)
        sc = score(r, base)
        rows.append((n, d, hbm, lp, share, f"{c.die_area_mm2:.0f}", f"{sc['eff_g']:.2f}× · {sc['eff_min']:.2f}×",
                     f"{sc['perf_g']:.2f}× · {sc['perf_min']:.2f}×", f"{sc['pmax']:.0f} W"))
    parts += ["## 1. Scorecard\n",
              "tok/J and perf are geometric mean · worst workload across the 7-workload suite.\n",
              _t(rows, ["", "What changes", "HBM", "LPDDR", "Weights from DDR", "Die mm²",
                        "tok/J", "Perf", "Peak W"]), ""]

    for key, title, fmt in (("eff", "Tokens per joule", "{:.2f}"), ("perf", "Throughput (tokens/s)", "{:,.0f}")):
        rows = []
        for i, (wname, *_x) in enumerate(SUITE):
            row = [wname, fmt.format(base[i][key])]
            for n, d, c, s, r in res[1:]:
                row.append("doesn't fit" if not r[i]["ok"] else f"{fmt.format(r[i][key])} ({r[i][key] / base[i][key]:.2f}×)")
            rows.append(row)
        parts += [f"## {2 if key == 'eff' else 3}. {title}\n",
                  _t(rows, ["Workload", "v0.2"] + [n for n, *_x in res[1:]]), ""]

    rows = []
    for i, (wname, *_x) in enumerate(SUITE):
        rows.append([wname] + [f"{r[i]['lat']} · {r[i]['power']:.0f} W" for n, d, c, s, r in res])
    parts += ["## 4. Latency and average power\n", _t(rows, ["Workload"] + [n for n, *_x in res]), ""]

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results", "memory_study.md")
    with open(path, "w") as f:
        f.write("\n".join(parts))
    print(open(path).read())


if __name__ == "__main__":
    main()
