"""One-knob-at-a-time sensitivity around the v0.2 design (variant D).

    python3 -m model.sensitivity      # writes results/sensitivity.md

Each row changes a single parameter and reports suite-wide tok/J and
throughput (geometric mean over the 7 workloads, and the worst workload)
relative to D, plus die area and peak average power.
"""
import os
from dataclasses import replace

from .hw import EnergyTable
from .study import D, SRV, evaluate, score, _t


def stacks(n):
    """n HBM3E stacks: bandwidth, capacity, PHY area and idle power scale together."""
    node = replace(D.node, fixed_static_w=D.node.fixed_static_w + 2.0 * (n - 4))
    return replace(D, hbm_stacks=n, hbm_tbps=1.2 * n, hbm_gb=36.0 * n, node=node)


def same_macs(dim):
    """Same total multipliers (48 x 128²), SRAM (192 MB) and vector throughput,
    split into fewer big tiles or more small ones. Per-tile router/vector area
    stays fixed in the area model, so small tiles pay for more routers."""
    f = dim ** 2 / 128 ** 2
    return replace(D, array_dim=dim, tiles=int(48 / f), weight_load_bytes_per_cycle=2 * dim,
                   sram_mb_per_tile=4.0 * f, vec_macs_per_cycle=int(1024 * f), vec_ops_per_cycle=int(512 * f),
                   node=replace(D.node, tile_static_w=D.node.tile_static_w * f))


KNOBS = [
    ("Compute tiles", "How many compute tiles (each a 128×128 array + 4 MB SRAM)",
     [(f"{t} tiles", replace(D, tiles=t), SRV) for t in (32, 40, 48, 56, 64)]),
    ("HBM stacks", "Memory stacks next to the die: bandwidth and capacity together",
     [(f"{n} stacks · {1.2 * n:.1f} TB/s · {36 * n} GB", stacks(n), SRV) for n in (3, 4, 6)]),
    ("HBM energy per byte", "Cost of each byte from HBM (HBM3E ≈ 30 pJ/B; HBM4 claims lower)",
     [(f"{pj} pJ/B", replace(D, energy=replace(EnergyTable(), hbm_pj_per_byte=pj)), SRV) for pj in (30, 25, 20, 15)]),
    ("Array size", "Same total multipliers, organised as fewer big arrays or more small ones",
     [(f"{d}×{d} arrays × {48 * 128 ** 2 // d ** 2} tiles", same_macs(d), SRV) for d in (64, 128, 256)]),
    ("Weight port", "Bytes of weights each tile can load per cycle",
     [(f"{b} B/cycle", replace(D, weight_load_bytes_per_cycle=b), SRV) for b in (128, 256, 512)]),
    ("LPDDR capacity tier", "Cheap memory for agents waiting on tools",
     [(f"{g} GB", replace(D, lpddr_gb=g), SRV) for g in (0, 128, 256, 512)]),
    ("Leakage", "Static power per tile (process corner / temperature)",
     [(f"{f:.0%} of nominal", replace(D, node=replace(D.node, tile_static_w=D.node.tile_static_w * f)), SRV)
      for f in (0.5, 1.0, 1.5)]),
    ("KV cache format", "Bytes stored per token of context",
     [("FP8 KV", D, SRV), ("FP4 KV", D, replace(SRV, kv_dtype="fp4")), ("BF16 KV", D, replace(SRV, kv_dtype="bf16"))]),
    ("Scheduler speed tolerance", "How much slower than the fastest option the chip may run to save energy",
     [(f"{t:.0%} slower allowed", replace(D, speed_slack=t), SRV) for t in (0.0, 0.02, 0.05, 0.10, 0.25)]),
    ("Speculative draft length", "Max tokens guessed ahead and verified in one step",
     [(f"k ≤ {k}", D, replace(SRV, spec_k=k)) for k in (0, 2, 4, 8)]),
]


def main():
    base = evaluate(D, SRV)
    parts = ["# Parameter sensitivity around v0.2 (variant D)\n",
             "_Generated by `python3 -m model.sensitivity`. One knob changes per row; everything else stays at D. "
             "Ratios vs D: **gmean** = typical workload, **worst** = weakest of the 7._\n"]
    summary = []
    for title, what, rows in KNOBS:
        out = []
        effs = []
        for label, chip, srv in rows:
            s = score(evaluate(chip, srv), base)
            effs.append(s["eff_g"])
            out.append((label, f"{s['eff_g']:.3f}×", f"{s['eff_min']:.2f}×", f"{s['perf_g']:.3f}×",
                        f"{s['perf_min']:.2f}×", f"{chip.die_area_mm2:.0f}", f"{s['pmax']:.0f} W"))
        summary.append((title, f"{min(effs):.2f}× – {max(effs):.2f}×", f"{(max(effs) / min(effs) - 1) * 100:.0f}%"))
        parts += [f"## {title}\n", f"_{what}_\n",
                  _t(out, ["Setting", "tok/J gmean", "tok/J worst", "Perf gmean", "Perf worst", "Die mm²", "Peak W"]), ""]
    summary.sort(key=lambda r: -float(r[2].rstrip("%")))
    parts[2:2] = ["## Ranking: how much each knob moves tok/J\n",
                  _t(summary, ["Knob", "tok/J range tried", "Spread"]), ""]
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results", "sensitivity.md")
    with open(path, "w") as f:
        f.write("\n".join(parts))
    print(open(path).read())


if __name__ == "__main__":
    main()
