"""Process-node and power-management study across a mixed workload suite.

    python3 -m model.study        # writes results/node_study.md

A variant "caters to all workloads" when its geometric-mean gain is high AND
no single workload regresses: both are reported.
"""
import math
import os
from dataclasses import replace

from .engine import decode_step, prefill
from .hw import N3, Chip, EnergyTable, Serving
from .run import CODING, RESEARCH
from .scenarios import run_agents, serve_chat
from .workloads import LLAMA_8B, LLAMA_70B, MIXTRAL_8X7B, ChatProfile

SRV = Serving(spec_k=4)
LONG = ChatProfile(name="long-context", prompt_tokens=32768, output_tokens=512, spec_accept=0.5)

SUITE = [
    ("Chat 8B, interactive (B=8)", "chat", LLAMA_8B, ChatProfile(), 8),
    ("Chat 8B, throughput (B=128)", "chat", LLAMA_8B, ChatProfile(), 128),
    ("Chat 70B (B=64)", "chat", LLAMA_70B, ChatProfile(), 64),
    ("MoE Mixtral-8x7B (B=64)", "chat", MIXTRAL_8X7B, ChatProfile(), 64),
    ("Long context 70B, 32k in (B=8)", "chat", LLAMA_70B, LONG, 8),
    ("Coding agent 70B", "agent", LLAMA_70B, CODING, "tiered-kv"),
    ("Research agent 8B", "agent", LLAMA_8B, RESEARCH, "tiered-kv"),
]

A = Chip(name="A")
B = replace(A, name="B", node=N3)
C = replace(B, name="C", dvfs="efficiency", power_gating=True)
D = replace(C, name="D", tiles=48)
E = replace(C, name="E", tiles=64)
F = replace(D, name="F", hbm_tbps=8.0, energy=replace(EnergyTable(), hbm_pj_per_byte=20.0))

VARIANTS = [
    (A, "N5, 32 tiles (current design)"),
    (B, "N3 port, same 32 tiles"),
    (C, "N3, 32 tiles + DVFS + array power gating"),
    (D, "N3, 48 tiles + DVFS + gating (same die area as A)"),
    (E, "N3, 64 tiles + DVFS + gating"),
    (F, "D + HBM4 (8 TB/s, 20 pJ/B)"),
]


def evaluate(chip: Chip, srv: Serving = SRV) -> list:
    out = []
    for name, kind, model, prof, arg in SUITE:
        if kind == "chat":
            r = serve_chat(model, chip, srv, prof, arg)
            out.append(dict(name=name, eff=r.tokens_per_j, perf=r.tokens_per_s,
                            lat=f"{r.tpot_ms:.1f} ms/tok", power=r.avg_power_w, ok=r.feasible))
        else:
            policy = arg if chip.has_capacity_tier else "hbm-cache"   # no capacity tier: KV stays in main memory
            r = run_agents(model, chip, srv, prof, policy)
            out.append(dict(name=name, eff=r.gen_tokens_per_j, perf=r.turns_per_s * prof.gen_tokens,
                            lat=f"{r.turn_latency_s:.1f} s/turn", power=r.avg_power_w,
                            ok=r.limiter != "weights don't fit"))
    return out


def gmean(xs):
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


def score(res, base):
    eff = [r["eff"] / b["eff"] for r, b in zip(res, base)]
    perf = [r["perf"] / b["perf"] for r, b in zip(res, base)]
    return dict(eff_g=gmean(eff), perf_g=gmean(perf), eff_min=min(eff), perf_min=min(perf),
                pmax=max(r["power"] for r in res))


def _t(rows, header):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    base = evaluate(A)
    results = {c.name: evaluate(c) for c, _ in VARIANTS}
    parts = ["# Process node and power study\n",
             "_Generated by `python3 -m model.study`. Every variant runs the same 7-workload suite. "
             "Ratios are against variant A. Energy assumptions: model/hw.py._\n"]

    parts += ["## 1. Variants\n", _t([
        (c.name, desc, c.node.name, c.tiles, f"{c.die_area_mm2:.0f}", f"{c.peak_tflops('fp8'):,.0f}",
         f"{c.hbm_tbps} TB/s", f"{c.static_w:.0f} / {c.idle_static_w:.0f} W", c.dvfs)
        for c, desc in VARIANTS],
        ["", "Variant", "Node", "Tiles", "Die mm²", "FP8 TFLOPS", "HBM", "Static nominal / idle", "DVFS"]), ""]

    rows = []
    for c, desc in VARIANTS:
        s = score(results[c.name], base)
        rows.append((f"**{c.name}**", desc, f"{s['eff_g']:.2f}×", f"{s['eff_min']:.2f}×",
                     f"{s['perf_g']:.2f}×", f"{s['perf_min']:.2f}×", f"{s['pmax']:.0f} W"))
    parts += ["## 2. Scorecard (suite geometric mean vs A)\n",
              "**Worst** columns show the weakest workload. A design that caters to all workloads keeps these ≥ 1.0.\n",
              _t(rows, ["", "Variant", "tok/J gmean", "tok/J worst", "Perf gmean", "Perf worst", "Peak avg power"]), ""]

    for metric, title, fmt in (("eff", "Energy efficiency (generated tokens per joule)", "{:.2f}"),
                               ("perf", "Throughput (generated tokens/s)", "{:,.0f}")):
        rows = []
        for i, (name, *_rest) in enumerate(SUITE):
            row = [name]
            for c, _ in VARIANTS:
                r = results[c.name][i]
                row.append("doesn't fit" if not r["ok"] else fmt.format(r[metric]))
            rows.append(row)
        parts += [f"## {3 if metric == 'eff' else 4}. {title}\n",
                  _t(rows, ["Workload"] + [c.name for c, _ in VARIANTS]), ""]

    rows = []
    for i, (name, *_rest) in enumerate(SUITE):
        rows.append([name] + [f"{results[c.name][i]['lat']} · {results[c.name][i]['power']:.0f} W" for c, _ in VARIANTS])
    parts += ["## 5. Latency and average power\n", _t(rows, ["Workload"] + [c.name for c, _ in VARIANTS]), ""]

    # which operating point the power manager picks, on D
    rows = []
    for label, fn in (("70B decode, B=64", lambda ch: decode_step(LLAMA_70B, ch, replace(SRV, spec_k=0), 64, 1280)),
                      ("8B decode, B=8", lambda ch: decode_step(LLAMA_8B, ch, replace(SRV, spec_k=0), 8, 1280)),
                      ("70B prefill, 4k", lambda ch: prefill(LLAMA_70B, ch, SRV, 4096)),
                      ("70B agent-turn prefill", lambda ch: prefill(LLAMA_70B, ch, SRV, 1200, 26000))):
        for pol in ("off", "efficiency", "performance"):
            c = fn(replace(D, dvfs=pol))
            rows.append((label, pol, f"{c.opp[0]:.3f} V / {c.opp[1]:.2f} GHz", f"{c.time_s * 1e3:.2f}",
                         f"{c.total_j:.2f}", f"{c.power_w:.0f}", c.bound))
    parts += ["## 6. Operating points chosen on variant D\n",
              "_off = always nominal (0.75 V / 1.2 GHz). efficiency = lowest energy within 2% of nominal speed. "
              "performance = fastest point under the 350 W TDP._\n",
              _t(rows, ["Step", "Policy", "Operating point", "Time ms", "Energy J", "Power W", "Bound"]), ""]

    # lever attribution on D
    levers = [
        ("D as designed", D, SRV),
        ("− DVFS (nominal clock only)", replace(D, dvfs="off"), SRV),
        ("− array power gating", replace(D, power_gating=False), SRV),
        ("− both (plain N3, 48 tiles)", replace(D, dvfs="off", power_gating=False), SRV),
        ("performance DVFS policy (boost)", replace(D, dvfs="performance"), SRV),
        ("+ FP4 KV cache", D, replace(SRV, kv_dtype="fp4")),
        ("+ FP4 activations (FP4×FP4 arrays)", D, replace(SRV, compute_dtype="fp4")),
    ]
    dres = results["D"]
    rows = []
    for label, chip, srv in levers:
        s = score(evaluate(chip, srv), dres)
        rows.append((label, f"{s['eff_g']:.3f}×", f"{s['eff_min']:.2f}×", f"{s['perf_g']:.3f}×",
                     f"{s['perf_min']:.2f}×", f"{s['pmax']:.0f} W"))
    parts += ["## 7. Lever attribution on D (ratios vs D)\n",
              _t(rows, ["Change", "tok/J gmean", "tok/J worst", "Perf gmean", "Perf worst", "Peak avg power"]), ""]

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results", "node_study.md")
    with open(path, "w") as f:
        f.write("\n".join(parts))
    print(open(path).read())


if __name__ == "__main__":
    main()
